### ISSUE TITLE
BUG: Marine Area Details Map UI

### ISSUE THREAD

**Issue by jeannechoi00** [info442-spr22/c-team#67]
**Minor Bug**
**General Summary:**
Really a minor bug that is just more visual stuff. If you click from the map or "checkout marine area" to get more details, the maps seems to enlarge when you hover over. Not sure if this was intentional but I don't think it's needed because the map ends up  covering the title and more below. 
**Environment it was encountered in:** Chrome
**Steps to reproduce:** 
- [ ] Remove hover effect feature on maps

**Expected result:** Static Map
**Actual result:** dynamic map that zooms in/gets larger when hovered over

Not hovered:
<img width="872" alt="Screen Shot 2022-05-18 at 9 09 11 AM" src="https://user-images.githubusercontent.com/76883010/169090437-dbd45ad6-eb5a-4949-8618-db84442afd86.png">

Hovered:
<img width="907" alt="Screen Shot 2022-05-18 at 9 09 34 AM" src="https://user-images.githubusercontent.com/76883010/169090512-13ca02da-94c5-4344-a151-8fdf90ce65aa.png">

**Comment by RachelChung2020** [comment]
Adding on, maybe create an option to enlarge the image after clicking on it instead of automatically when user hovers.

**Comment by spudists** [comment]
Work worth doing.  Will accomplish in the next sprint.  Remove one line of CSS code to remove size increase on hover
