### ISSUE TITLE
Major Bug: the species button on the explore page does not respond

### ISSUE THREAD

**Issue by xxiaouw** [info442-spr22/c-team#69]
On the explore page, when I clicked on the species button, nothing happened. I was expecting to be redirected to another page, or to see more content. The actual response was nothing happened.

**Comment by cherimarie** [comment]
I can't repro this on Chrome on MacOS. I think only the text on the button is a click target, maybe @xxiaouw clicked on larger area of button? It would be reasonable for a user to expect the entire button to be clickable. I'd categorize this as a minor bug.

**Comment by spudists** [comment]
Minor Bug.  We can expand the event item to include the entire card instead of just the text.

**Comment by spudists** [comment]
Resolved with above changes
