### ISSUE TITLE
closer titles to links (minor)

### ISSUE THREAD

**Issue by hadardolev** [info442-spr22/c-team#71]
On the get involved page, the petition and donation titles are a bit far from the links making it hard to see a relationship between them. I suggest formating them so they are close together.

**Comment by abequette99** [comment]
Work worth doing. This will be completed in the next sprint. We will copy the format of the explore page but change out the content to make it look cleaner.

**Comment by spudists** [comment]
Resolved with SP-71.  Left bound donation links to move them under the headers.
