### ISSUE TITLE
[Minor Bug] Navigation Bar Text is All Clumped Together on Mobile

### ISSUE THREAD

**Issue by soshikun** [info442-spr22/c-team#72]
As the title says, the navigation bar's text are all clumped together on mobile. Maneuvering through the site is very difficult as I'm not sure which words go to a different page and which words are together. The navigation bar words are wrapping in a way that a user can be confused as to what word goes to what page. For example, if I read by going downwards, I would see "Map Involved Us", which doesn't sound right.

Safari on iPhone XR

Steps to Reproduce:
1. Go to site on Safari on a mobile device
2. Look at navigation bar

Expected Result: Words on the navigation bar are separated clearly.
Actual Result: Words on the navigation bar are not separated and are wrapping around each other. They are very clumped up together.

**Comment by pranavshekar** [comment]
Additional Info: The nav bar is messed up on this page but also when you scroll down, the text cuts off at a weird point. This is more of a visual minor bug. The map is also way bigger than everything else as evident in the picture. 

![IMG_9824](https://user-images.githubusercontent.com/62967217/169094022-7dcf31f4-2888-4240-8f8f-8fe6521def35.PNG)

**Comment by sharlenef** [comment]
In addition, when on a smaller window size (on a laptop), the navbar and titles clump together

Tested on: Chrome Version 101.0.4951.54 on macOS Big Sur

Reproduce by: 

1. Going on site on desktop/laptop
2. Make window size small (to the smallest option)

<img width="492" alt="Screen Shot 2022-05-18 at 9 42 18 AM" src="https://user-images.githubusercontent.com/70997571/169097138-29532849-706b-4612-bc47-388fbe7f8aa2.png">

**Comment by abequette99** [comment]
duplicate: https://github.com/info442-spr22/c-team/issues/68 

In our requirements, we have a certain screen size that we make the application for. We will think about working on trying to fix the nav bar and text so it does not get clumped together.
