### ISSUE TITLE
Un-scrollable Explore Page (minor bug)

### ISSUE THREAD

**Issue by nihagaddam** [info442-spr22/c-team#75]
Summary: The explore page is cut short because it does not include the footer bar with citations, therefore creating the page un-scrollable. 
Environment: Chrome
Steps to reproduce: Click on "Explore" in Navbar, use down arrow or mousepad to scroll down to see footer.
Expected result: Footer should be present to see citations. 
Actual result: Footer cannot be seen because page is un-scrollable/footer not present.

**Comment by abequette99** [comment]
Work worth fixing. We will add a footer to make the page completely scrollable.

**Comment by spudists** [comment]
Issue resolved, extended page length
