### ISSUE TITLE
[Enhancement] Back buttons after selecting explore options

### ISSUE THREAD

**Issue by kasayachith** [info442-spr22/c-team#76]
Currently, after pressing on either "species" or "marine areas", the only way to get back to the explore page is by pressing "explore" on the navigation bar. However, I keep accidentally clicking one and wanting to go back so it would be helpful if there were back buttons that take you back to the explore options.

**Comment by abequette99** [comment]
Work worth fixing. We will add a back button to our species and marine area pages to get back to the explore page.
