### ISSUE TITLE
[Slightly Minor Bug] Cannot zoom out on the map on mobile

### ISSUE THREAD

**Issue by soshikun** [info442-spr22/c-team#77]
I wanted to see all of the marine areas on the map so I tried to zoom out, but it wouldn't let me zoom out. I am only able to drag through the map to see the marine areas.

Safari on iPhone XR

Steps to Reproduce:
1. Open the site on Safari on a mobile device
2. Try to zoom out on the map with two fingers.

Expected Result: Map will zoom out and I will be able to see all of the marine areas available.

Actual Result: Map refuses to zoom out and goes back to the starting zoom level.

**Comment by abequette99** [comment]
Invalid. In our requirements, we state that our platform will only be used on a platform 1300pixels or larger.
