### ISSUE TITLE
Minor bug: Fish missing description

### ISSUE THREAD

**Issue by sharlenef** [info442-spr22/c-team#81]
While going through the fishes species, some descriptions have missing information or have things like *DEPTH RANGE* and *LOCATION*

Tested on: Chrome Version 101.0.4951.54 on macOS Big Sur

Steps to reproduce:

1. From Home, click explore
2. Click the species button
3. Click button for checking out Pacific Steelhead

Expected result: fish has description written out

Actual result: no description for fish

<img width="1225" alt="Screen Shot 2022-05-18 at 9 40 01 AM" src="https://user-images.githubusercontent.com/70997571/169096383-b14afb71-e13f-44b2-a44d-6d297b8e60b5.png">

**Comment by abequette99** [comment]
Need to fix. This is an error in our database labeling.
