### ISSUE TITLE
(Very minor bug) Change user cursor when dragging the map

### ISSUE THREAD

**Issue by fretws** [info442-spr22/c-team#83]
Steps to recreate: Navigate to map page, click and drag on map
Expected result: Cursor will change from open hand to grasping hand, and I can drag to move around on the map
Actual result: I can drag to move around on the map, but the hand remains open
Windows 10, Chrome

**Comment by abequette99** [comment]
Can not recreate it. Tested on google chrome Windows 11 and 10 and mac os Monterey and we did not run into this issue.
