### ISSUE TITLE
Minor Bug: The picture in detail pages are blocking the title

### ISSUE THREAD

**Issue by LouisXO** [info442-spr22/c-team#84]
After hovering over the image, it gets bigger and blocks some of the text.
Chrome Version 101.0.4951.64 (Official Build) (arm64)
macOS Monterey

**Comment by avaghela-1925502** [comment]
Ran into the same error, could make add an option to click the image to see if better and have it take up the whole screen. Expected to see the image without it covering the text but the actual result ended up covering the text.

**Comment by spasion5023** [comment]
Duplicate #67
