### ISSUE TITLE
Enhancement: Change the font color after clicking on a species and scrolling down to the fish description 

### ISSUE THREAD

**Issue by hannanajmal** [info442-spr22/c-team#86]
Something to considered if you wanted to but, the all green under the description for the fishes was a little hard to read at first. maybe that's because it's early in the morning but, maybe keeping the tittles for example: chum salmon location and fish description as a green color and then the text after that to black might make it look better? very small suggestion

**Comment by spasion5023** [comment]
Changes were made in an unpushed branch. Will be added in the current sprint.
