### ISSUE TITLE
Enhancement: Change Explore Page Button Size (Minor)

### ISSUE THREAD

**Issue by pranavshekar** [info442-spr22/c-team#87]
On Google Chrome Version 100.0.4896.127 on a 2019 Macbook Air when you go to the Explore page the button sizing for 'Species' and 'Marine Areas' is just really big. I would suggest making the boxes smaller. Especially because you can only click on the boxes by clicking on the text instead of the surrounding areas. I think this would be useful because it would be more intuitive for the user and more accessible. This is because they might click on the surrounding box area and find it not clickable even though it technically is. 

<img width="1435" alt="Screen Shot 2022-05-18 at 9 57 03 AM" src="https://user-images.githubusercontent.com/62967217/169100579-0600c1de-6c9d-488d-80ce-cf72fa3bad98.png">

**Comment by pranavshekar** [comment]
You could also just make the surrounding area of the boxes clickable (the green parts)

**Comment by spasion5023** [comment]
Plan on fixing boxes and will adjust hovering accordingly.
