### ISSUE TITLE
(Enhancement) Making any parts of the cards (for the Marine Areas) clickable

### ISSUE THREAD

**Issue by soopark82** [info442-spr22/c-team#90]
![image](https://user-images.githubusercontent.com/63069316/169098966-3e445c94-3e05-4013-87bc-48840078fcac.png)

I'd suggest adding a hovering effect to the buttons to make it even more apparent that the users should click on them to view the details of the different Marine Areas or I'd suggest making the cards (for the Marine Areas) themselves clickable. The drop shadow on these cards makes me think I could just click on any parts of the cards to view the details. This is a tedious detail but something that could definitely enhance your app in terms of UI.

**Comment by spasion5023** [comment]
Will adjust CSS for the whole card to turn green when hovered over.
