### ISSUE TITLE
Enhancement: Footer standardized across all pages

### ISSUE THREAD

**Issue by aidanthorns** [info442-spr22/c-team#93]
One page has an empty footer, one has no footer, one has a footer with citations and one has a footer that says citaitons but no citations. Standardizing the footer in any way across all pages could improve the cleanness of the app and make the app feel more connected.

**Comment by spasion5023** [comment]
Footer differences are noticed. A consistent footer will be added.

**Comment by spudists** [comment]
Resolved with sp-93.  Removed unwanted citation in footer of the Get Involved page
