### ISSUE TITLE
Minor Bug: Footer disappears on get involved page when resizing

### ISSUE THREAD

**Issue by aidanthorns** [info442-spr22/c-team#94]
On the Get Inolved page there is a stacked footer, the bottom white space is empty. When resizing to any size that isn't full desktop this white area disappears. Consider removing the white footer or making sure it scales to different sizes.
Without Footer:
![without_footer](https://user-images.githubusercontent.com/72417018/169219681-7c25fb09-540b-45f0-b8a7-3f1a2083ef16.PNG)
With Footer:
![with_footer](https://user-images.githubusercontent.com/72417018/169219688-100cb6df-2775-4730-8876-bf09cf543b10.PNG)

**Comment by spasion5023** [comment]
Duplicate #91
