### ISSUE TITLE
Enhancement: Remove underlines of non links

### ISSUE THREAD

**Issue by aidanthorns** [info442-spr22/c-team#96]
The title is undelined on the map and explore page, while the get involved and about page do not have underlined titles. Typically text that is underlined has a link attached to it. Removing this underlining could make it more clear to the user that it is not a link and is instead a title.

**Comment by spasion5023** [comment]
Color differences occur on different pages. We will address this in CSS for this coming sprint.

**Comment by spudists** [comment]
Resolved with sp-93.  Standardized CSS elements of headers
