### ISSUE TITLE
[Enhancement] Add more supporting images throughout

### ISSUE THREAD

**Issue by mariamk-2740** [info442-spr22/c-team#98]
You all have a great site, but perhaps adding helpful images like to the boxes in the picture below will be more attractive to the audience. Having visual elements to support words can support the experience. 

<img width="1440" alt="Screen Shot 2022-05-18 at 11 07 32 PM" src="https://user-images.githubusercontent.com/62913860/169222179-c92b7a64-ce2e-4d36-8527-44ba90d0c911.png">

**Comment by spasion5023** [comment]
There is a similar issue we are addressing and we will be adding images to these boxes in the current sprint.
