### ISSUE TITLE
(Enhancement) add marine area information page to the navbar for easier navigation

### ISSUE THREAD

**Issue by Yueemxn** [info442-spr22/c-team#99]
- Description of the requested feature
  - Add the marine area detail page (the one we see after we click on "return" on a marine area profile) so the users can access the page directly from homepage. The return link now should redirect the users back to the homepage.
- Explanation of why it would be useful
  - It would save time for users during navigation since now they can navigate back to the homepage through one click and have options to either check out details about a certain marine area either through the map or a collection of marine area detail cards.

**Comment by spasion5023** [comment]
Invalid as this was an intentional design decision from our requirements.
